baseURL = 'https://757local.pages.dev/'
locale = 'en-us'
title = '757 Local'
theme = '757local-theme'

[params]
  description = "The Premier Local Directory for Hampton Roads Makers & Businesses"
  tagline = "Get found when people ask AI for local"
